# important functions according to:
# http://www.g-truc.net/post-0631.html#menu

###
	GLAPI void APIENTRY glAttachShader (GLuint program, GLuint shader);
	GLAPI void APIENTRY glBeginConditionalRender (GLuint id, GLenum mode);
	GLAPI void APIENTRY glBeginQueryIndexed (GLenum target, GLuint index, GLuint id);
	GLAPI void APIENTRY glBeginTransformFeedback (GLenum primitiveMode);
	GLAPI void APIENTRY glBindBuffer (GLenum target, GLuint buffer);
	GLAPI void APIENTRY glBindBuffersBase (GLenum target, GLuint first, GLsizei count, const GLuint *buffers);
	GLAPI void APIENTRY glBindBuffersRange (GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes);
	GLAPI void APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer);
	GLAPI void APIENTRY glBindImageTextures (GLuint first, GLsizei count, const GLuint *textures);
	GLAPI void APIENTRY glBindProgramPipeline (GLuint pipeline);
	GLAPI void APIENTRY glBindSamplers (GLuint first, GLsizei count, const GLuint *samplers);
	GLAPI void APIENTRY glBindTextures (GLuint first, GLsizei count, const GLuint *textures);
	GLAPI void APIENTRY glBindTransformFeedback (GLenum target, GLuint id);
	GLAPI void APIENTRY glBindVertexArray (GLuint array);
	GLAPI void APIENTRY glBlendColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
	GLAPI void APIENTRY glBlendEquationSeparatei (GLuint buf, GLenum modeRGB, GLenum modeAlpha);
	GLAPI void APIENTRY glBlendFuncSeparatei (GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
	GLAPI void APIENTRY glBlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
	GLAPI void APIENTRY glBufferStorage (GLenum target, GLsizeiptr size, const void *data, GLbitfield flags);
	GLAPI void APIENTRY glClampColor (GLenum target, GLenum clamp);
	GLAPI void APIENTRY glClearBufferiv (GLenum buffer, GLint drawbuffer, const GLint *value);
	GLAPI void APIENTRY glClearBufferuiv (GLenum buffer, GLint drawbuffer, const GLuint *value);
	GLAPI void APIENTRY glClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat *value);
	GLAPI void APIENTRY glClearBufferfi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
	GLAPI void APIENTRY glClearBufferData (GLenum target, GLenum internalformat, GLenum format, GLenum type, const void *data);
#	GLAPI void APIENTRY glClearBufferSubData (GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
	GLAPI void APIENTRY glClearTexImage (GLuint texture, GLint level, GLenum format, GLenum type, const void *data);
	GLAPI void APIENTRY glClearTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data);
	GLAPI GLenum APIENTRY glClientWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout);
	GLAPI void APIENTRY glColorMaski (GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
	GLAPI void APIENTRY glCompileShader (GLuint shader);
	GLAPI void APIENTRY glCompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
	GLAPI void APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
	GLAPI void APIENTRY glCompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
	GLAPI void APIENTRY glCopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
	GLAPI void APIENTRY glCopyImageSubData (GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
	GLAPI void APIENTRY glCopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
	GLAPI void APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
	GLAPI void APIENTRY glCopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
	GLAPI GLuint APIENTRY glCreateProgram (void);
	GLAPI GLuint APIENTRY glCreateShader (GLenum type);
	GLAPI void APIENTRY glCullFace (GLenum mode);
	GLAPI void APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers);
	GLAPI void APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers);
	GLAPI void APIENTRY glDeleteProgram (GLuint program);
	GLAPI void APIENTRY glDeleteProgramPipelines (GLsizei n, const GLuint *pipelines);
	GLAPI void APIENTRY glDeleteQueries (GLsizei n, const GLuint *ids);
	GLAPI void APIENTRY glDeleteSamplers (GLsizei count, const GLuint *samplers);
	GLAPI void APIENTRY glDeleteShader (GLuint shader);
	GLAPI void APIENTRY glDeleteSync (GLsync sync);
	GLAPI void APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures);
	GLAPI void APIENTRY glDeleteTransformFeedbacks (GLsizei n, const GLuint *ids);
	GLAPI void APIENTRY glDeleteVertexArrays (GLsizei n, const GLuint *arrays);
	GLAPI void APIENTRY glDepthRangeArrayv (GLuint first, GLsizei count, const GLdouble *v);
	GLAPI void APIENTRY glDepthFunc (GLenum func);
	GLAPI void APIENTRY glDepthMask (GLboolean flag);
	GLAPI void APIENTRY glDetachShader (GLuint program, GLuint shader);
	GLAPI void APIENTRY glDisable (GLenum cap);
	GLAPI void APIENTRY glDisablei (GLenum target, GLuint index);
	GLAPI void APIENTRY glDispatchCompute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
	GLAPI void APIENTRY glDispatchComputeIndirect (GLintptr indirect);
	GLAPI void APIENTRY glDrawArraysInstancedBaseInstance (GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
	GLAPI void APIENTRY glDrawBuffers (GLsizei n, const GLenum *bufs);
	GLAPI void APIENTRY glDrawElementsInstancedBaseVertexBaseInstance (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
	GLAPI void APIENTRY glDrawTransformFeedbackStreamInstanced (GLenum mode, GLuint id, GLuint stream, GLsizei instancecount);
	GLAPI void APIENTRY glEnable (GLenum cap);
	GLAPI void APIENTRY glEnablei (GLenum target, GLuint index);
	GLAPI void APIENTRY glEndConditionalRender (void);
	GLAPI void APIENTRY glEndQueryIndexed (GLenum target, GLuint index);
	GLAPI void APIENTRY glEndTransformFeedback (void);
	GLAPI GLsync APIENTRY glFenceSync (GLenum condition, GLbitfield flags);
	GLAPI void APIENTRY glFinish (void);
	GLAPI void APIENTRY glFlush (void);
	GLAPI void APIENTRY glFlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length);
	GLAPI void APIENTRY glFramebufferParameteri (GLenum target, GLenum pname, GLint param);
	GLAPI void APIENTRY glFramebufferTexture (GLenum target, GLenum attachment, GLuint texture, GLint level);
#	GLAPI void APIENTRY glFramebufferTexture1D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
#	GLAPI void APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
#	GLAPI void APIENTRY glFramebufferTexture3D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
	GLAPI void APIENTRY glFramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
	GLAPI void APIENTRY glFrontFace (GLenum mode);
	GLAPI void APIENTRY glGenBuffers (GLsizei n, GLuint *buffers);
	GLAPI void APIENTRY glGenerateMipmap (GLenum target);
	GLAPI void APIENTRY glGenFramebuffers (GLsizei n, GLuint *framebuffers);
	GLAPI void APIENTRY glGenProgramPipelines (GLsizei n, GLuint *pipelines);
	GLAPI void APIENTRY glGenQueries (GLsizei n, GLuint *ids);
	GLAPI void APIENTRY glGenSamplers (GLsizei count, GLuint *samplers);
	GLAPI void APIENTRY glGenTextures (GLsizei n, GLuint *textures);
	GLAPI void APIENTRY glGenTransformFeedbacks (GLsizei n, GLuint *ids);
	GLAPI void APIENTRY glGenVertexArrays (GLsizei n, GLuint *arrays);
	GLAPI void APIENTRY glInvalidateBufferData (GLuint buffer);
	GLAPI void APIENTRY glInvalidateBufferSubData (GLuint buffer, GLintptr offset, GLsizeiptr length);
	GLAPI void APIENTRY glInvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments);
	GLAPI void APIENTRY glInvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
	GLAPI void APIENTRY glInvalidateTexImage (GLuint texture, GLint level);
	GLAPI void APIENTRY glInvalidateTexSubImage (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth);
	GLAPI void APIENTRY glLineWidth (GLfloat width);
	GLAPI void APIENTRY glLinkProgram (GLuint program);
	GLAPI void APIENTRY glLogicOp (GLenum opcode);
	GLAPI void *APIENTRY glMapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
	GLAPI void APIENTRY glMemoryBarrier (GLbitfield barriers);
	GLAPI void APIENTRY glMinSampleShading (GLfloat value);
	GLAPI void APIENTRY glMultiDrawArraysIndirect (GLenum mode, const void *indirect, GLsizei drawcount, GLsizei stride);
	GLAPI void APIENTRY glMultiDrawElementsIndirect (GLenum mode, GLenum type, const void *indirect, GLsizei drawcount, GLsizei stride);
	GLAPI void APIENTRY glPatchParameterfv (GLenum pname, const GLfloat *values);
	GLAPI void APIENTRY glPatchParameteri (GLenum pname, GLint value);
	GLAPI void APIENTRY glPauseTransformFeedback (void);
	GLAPI void APIENTRY glPixelStoref (GLenum pname, GLfloat param);
	GLAPI void APIENTRY glPixelStorei (GLenum pname, GLint param);
	GLAPI void APIENTRY glPointParameterfv (GLenum pname, const GLfloat *params);
	GLAPI void APIENTRY glPointParameteriv (GLenum pname, const GLint *params);
	GLAPI void APIENTRY glPointSize (GLfloat size);
	GLAPI void APIENTRY glPolygonMode (GLenum face, GLenum mode);
	GLAPI void APIENTRY glPolygonOffset (GLfloat factor, GLfloat units);
	GLAPI void APIENTRY glPrimitiveRestartIndex (GLuint index);
	GLAPI void APIENTRY glProgramBinary (GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
	GLAPI void APIENTRY glProgramParameteri (GLuint program, GLenum pname, GLint value);
	GLAPI void APIENTRY glProvokingVertex (GLenum mode);
	GLAPI void APIENTRY glQueryCounter (GLuint id, GLenum target);
	GLAPI void APIENTRY glReadBuffer (GLenum mode);
	GLAPI void APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
	GLAPI void APIENTRY glReleaseShaderCompiler (void);
	GLAPI void APIENTRY glResumeTransformFeedback (void);
	GLAPI void APIENTRY glSampleCoverage (GLfloat value, GLboolean invert);
	GLAPI void APIENTRY glSampleMaski (GLuint maskNumber, GLbitfield mask);
#	GLAPI void APIENTRY glSamplerParameterf (GLuint sampler, GLenum pname, GLfloat param);
	GLAPI void APIENTRY glSamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat *param);
	GLAPI void APIENTRY glSamplerParameterIiv (GLuint sampler, GLenum pname, const GLint *param);
	GLAPI void APIENTRY glSamplerParameterIuiv (GLuint sampler, GLenum pname, const GLuint *param);
#	GLAPI void APIENTRY glSamplerParameteri (GLuint sampler, GLenum pname, GLint param);
	GLAPI void APIENTRY glSamplerParameteriv (GLuint sampler, GLenum pname, const GLint *param);
	GLAPI void APIENTRY glScissorArrayv (GLuint first, GLsizei count, const GLint *v);
	GLAPI void APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
	GLAPI void APIENTRY glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask);
	GLAPI void APIENTRY glStencilMaskSeparate (GLenum face, GLuint mask);
	GLAPI void APIENTRY glStencilOpSeparate (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
	GLAPI void APIENTRY glTexBuffer (GLenum target, GLenum internalformat, GLuint buffer);
	GLAPI void APIENTRY glTexBufferRange (GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
#	GLAPI void APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param);
	GLAPI void APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params);
	GLAPI void APIENTRY glTexParameterIiv (GLenum target, GLenum pname, const GLint *params);
	GLAPI void APIENTRY glTexParameterIuiv (GLenum target, GLenum pname, const GLuint *params);
#	GLAPI void APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param);
	GLAPI void APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint *params);
	GLAPI void APIENTRY glTexStorage1D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
	GLAPI void APIENTRY glTexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
	GLAPI void APIENTRY glTexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
	GLAPI void APIENTRY glTexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
	GLAPI void APIENTRY glTexStorage3DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
	GLAPI void APIENTRY glTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
	GLAPI void APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
	GLAPI void APIENTRY glTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
	GLAPI void APIENTRY glTextureView (GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers);
	GLAPI GLboolean APIENTRY glUnmapBuffer (GLenum target);
	GLAPI void APIENTRY glUseProgramStages (GLuint pipeline, GLbitfield stages, GLuint program);
	GLAPI void APIENTRY glViewportArrayv (GLuint first, GLsizei count, const GLfloat *v);
	GLAPI void APIENTRY glWaitSync (GLsync sync, GLbitfield flags, GLuint64 timeout);

#below still need to be added to opengl-4-4-class.coffee

	Debugging API:
	
	GLAPI void APIENTRY glDebugMessageCallback (GLDEBUGPROC callback, const void *userParam);
	GLAPI void APIENTRY glDebugMessageControl (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
	GLAPI void APIENTRY glDebugMessageInsert (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
	GLAPI GLenum APIENTRY glCheckFramebufferStatus (GLenum target);
	GLAPI void APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
	GLAPI void APIENTRY glGetProgramPipelineiv (GLuint pipeline, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetProgramPipelineInfoLog (GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
	GLAPI void APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
	GLAPI void APIENTRY glObjectLabel (GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
	GLAPI void APIENTRY glObjectPtrLabel (const void *ptr, GLsizei length, const GLchar *label);
	GLAPI void APIENTRY glPopDebugGroup (void);
	GLAPI void APIENTRY glPushDebugGroup (GLenum source, GLuint id, GLsizei length, const GLchar *message);
	GLAPI void APIENTRY glValidateProgramPipeline (GLuint pipeline);
	
	Reflexion API (only for tools developers):
	
	GLAPI void APIENTRY glGetActiveAtomicCounterBufferiv (GLuint program, GLuint bufferIndex, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetActiveUniform (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
	GLAPI void APIENTRY glGetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetActiveUniformBlockName (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
	GLAPI void APIENTRY glGetActiveUniformName (GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName);
	GLAPI void APIENTRY glGetActiveUniformsiv (GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
	GLAPI void APIENTRY glGetBooleani_v (GLenum target, GLuint index, GLboolean *data);
	GLAPI void APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetBufferParameteri64v (GLenum target, GLenum pname, GLint64 *params);
	GLAPI void APIENTRY glGetFloati_v (GLenum target, GLuint index, GLfloat *data);
	GLAPI void APIENTRY glGetFloatv (GLenum pname, GLfloat *data);
	GLAPI void APIENTRY glGetInteger64i_v (GLenum target, GLuint index, GLint64 *data);
	GLAPI void APIENTRY glGetInteger64v (GLenum pname, GLint64 *data);
	GLAPI void APIENTRY glGetIntegeri_v (GLenum target, GLuint index, GLint *data);
	GLAPI void APIENTRY glGetIntegerv (GLenum pname, GLint *data);
	GLAPI void APIENTRY glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetFramebufferParameteriv (GLenum target, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetInternalformati64v (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint64 *params);
	GLAPI void APIENTRY glGetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params);
	GLAPI void APIENTRY glGetMultisamplefv (GLenum pname, GLuint index, GLfloat *val);
	GLAPI void APIENTRY glGetObjectLabel (GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
	GLAPI void APIENTRY glGetObjectPtrLabel (const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);
	GLAPI void APIENTRY glGetProgramBinary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
	GLAPI void APIENTRY glGetProgramInterfaceiv (GLuint program, GLenum programInterface, GLenum pname, GLint *params);
	GLAPI GLuint APIENTRY glGetProgramResourceIndex (GLuint program, GLenum programInterface, const GLchar *name);
	GLAPI void APIENTRY glGetProgramResourceiv (GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
	GLAPI GLint APIENTRY glGetProgramResourceLocationIndex (GLuint program, GLenum programInterface, const GLchar *name);
	GLAPI void APIENTRY glGetProgramResourceName (GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
	GLAPI void APIENTRY glGetProgramStageiv (GLuint program, GLenum shadertype, GLenum pname, GLint *values);
	GLAPI void APIENTRY glGetQueryIndexediv (GLenum target, GLuint index, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetQueryiv (GLenum target, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetQueryObjecti64v (GLuint id, GLenum pname, GLint64 *params);
	GLAPI void APIENTRY glGetQueryObjectiv (GLuint id, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetQueryObjectui64v (GLuint id, GLenum pname, GLuint64 *params);
	GLAPI void APIENTRY glGetQueryObjectuiv (GLuint id, GLenum pname, GLuint *params);
	GLAPI void APIENTRY glGetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat *params);
	GLAPI void APIENTRY glGetSamplerParameterIiv (GLuint sampler, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetSamplerParameterIuiv (GLuint sampler, GLenum pname, GLuint *params);
	GLAPI void APIENTRY glGetSamplerParameteriv (GLuint sampler, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
	GLAPI void APIENTRY glGetShaderSource (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
	GLAPI void APIENTRY glGetSynciv (GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
	GLAPI void APIENTRY glGetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params);
	GLAPI void APIENTRY glGetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params);
	GLAPI void APIENTRY glGetTexParameterIiv (GLenum target, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetTexParameterIuiv (GLenum target, GLenum pname, GLuint *params);
	GLAPI void APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint *params);
	GLAPI void APIENTRY glGetTransformFeedbackVarying (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
###